name: Deploy Workflow

on:
  workflow_run:
    workflows: [ "Pull Request Workflow" ]
    types:
      - completed

jobs:
  Deploy:
    name: Deploy To Virtual Server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      # Step 3: Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Step 4: Merge Pull Request
      - name: Merge Pull Request
        run: |
          gh pr merge ${{ github.event.inputs.pr_number }} --merge --auto -R aigul-ermak/NestBloggerAuthAPI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Deploy Application
      - name: Deploy Application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VS_SSH_KEY }}
          HOST: ${{ secrets.VIRTUAL_SERVER_HOST }}
          USER: ${{ secrets.VIRTUAL_SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $USER@$HOST << 'EOF'
             cd /home/projects/NestBloggerAuthAPI
             git pull origin main
             yarn install --production
             pm2 restart NestBloggerAuthAPI
          EOF
