name: Deploy Workflow

on:
  workflow_run:
    workflows:
      - Pull Request Workflow
    types:
      - completed

jobs:
  Deploy:
    name: Deploy To Virtual Server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Merge Pull Request
        run: |
          gh pr merge $(gh pr list --state open --json number --jq ".[0].number") --merge --auto -R aigul-ermak/NestBloggerAuthAPI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VS_SSH_KEY }}
          HOST: ${{ secrets.VIRTUAL_SERVER_HOST }}
          USER: ${{ secrets.VIRTUAL_SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $USER@$HOST << 'EOF'
             cd /home/projects/NestBloggerAuthAPI
             git pull origin main
             yarn install --production
             pm2 restart NestBloggerAuthAPI
          EOF
