name: Pull Request Workflow

on:
  workflow_run:
    workflows:
      - Test Workflow
    types:
      - completed

jobs:
  CreatePullRequest:
    name: Create Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging
          base: main
          title: 'Merge staging into main'
          body: |
            This pull request merges changes from staging into main after successful tests.
          draft: false
      - name: Output Pull Request Number
        run:
        echo "Pull Request Number: ${{ steps.create_pr.outputs.pull-request-number }}"
