name: GitHub Actions Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - staging

jobs:
  Tests:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Install dependencies
      - name: Install dependencies
        run: yarn

      # Step 3: Run e2e tests
      - name: Test
        run: yarn test:e2e

  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: Tests
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Step 3: Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Step 4: Build Project Artifacts
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Step 5: Deploy Project Artifacts to Vercel
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
