name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

jobs:
  Tests:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Enable Corepack and Use Specific Yarn Version
      - name: Enable Corepack
        run: corepack enable

      - name: Use Specific Yarn Version
        run: corepack prepare yarn@4.4.0 --activate

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Run e2e tests
      - name: Test
        env:
          HTTP_BASIC_USER: ${{ secrets.HTTP_BASIC_USER }}
          HTTP_BASIC_PASS: ${{ secrets.HTTP_BASIC_PASS }}
          MONGO_CONNECTION_URI_FOR_TESTS: ${{ secrets.MONGO_CONNECTION_URI_FOR_TESTS }}
        run: yarn test:e2e

  Deploy:
    name: Deploy To Virtual Server
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout main branch
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      # Step 2: Merge staging into main
      - name: Merge staging into main
        run: |
          git config --global user.name "aigul-ermak"
          git config --global user.email "aigul.erma@gmail.com"
          git checkout main
          git merge staging
          git push origin main

      # Step 3: Deploy to Virtual Server
      - name: Deploy Application
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VS_SSH_KEY }}
          HOST: ${{ secrets.VIRTUAL_SERVER_HOST }}
          USER: ${{ secrets.VIRTUAL_SERVER_USER }}
        run: |
          echo "Deploying to Virtual Server"
          ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $USER@$HOST << 'EOF'
            cd /home/projects/NestBloggerAuthAPI
            git pull origin main
            yarn install --production
            pm2 restart NestBloggerAuthAPI
          EOF
