name: CI/CD Pipeline

on:
  push:
    branches:
      - staging

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Tests:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the cod
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Enable Corepack and Use Specific Yarn Version
      - name: Enable Corepack
        run: corepack enable

      - name: Use Specific Yarn Version
        run: corepack prepare yarn@4.4.0 --activate

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install


      # Step 4: Run e2e tests
      - name: Test
        env:
          ENV: TEST
          MONGO_CONNECTION_URI_FOR_TESTS: ${{ secrets.MONGO_CONNECTION_URI_FOR_TESTS }}
        run: |
          echo "Running End-to-End Tests"
          yarn test:e2e || echo "Tests failed with exit code $?"
        continue-on-error: true

  Deploy-Preview:
    name: Deploy Vercel Preview
    runs-on: ubuntu-latest
    needs: Tests
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Step 3: Pull Vercel Environment Information
      - name: Pull Vercel Environment Information
        env:
          MONGO_CONNECTION_URI: ${{ secrets.MONGO_CONNECTION_URI }}
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Step 4: Build Project Artifacts
      - name: Build Project Artifacts
        env:
          MONGO_CONNECTION_URI: ${{ secrets.MONGO_CONNECTION_URI }}
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Step 5: Deploy Project Artifacts to Vercel
      - name: Deploy Project Artifacts to Vercel
        env:
          MONGO_CONNECTION_URI: ${{ secrets.MONGO_CONNECTION_URI }}
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
